### ISSUE TITLE
Failing tests with python 3.10

### ISSUE THREAD

**Issue by dvzrv** [ashb/sphinx-argparse#5]
Hi! When building this for Arch Linux, there are a bunch of failing tests, due to changes in argparse's naming of things.

Full build log: 
[sphinx-argparse-0.3.1-build.log](https://github.com/ashb/sphinx-argparse/files/7652841/sphinx-argparse-0.3.1-build.log)

**Comment by ashb** [comment]
Fixed by #3, I'll release a new version shortly. (Better late than never right?)
